### ISSUE TITLE
Give more precise toots creation date/time

### ISSUE THREAD

**Issue by kit-ty-kate** [stom79/mastalab#346] opened 2018-03-02 14:33 UTC
It would be awesome to have the precise time and date for the currently selected toot like the webapp does, instead of having "1d" or something like that.

---

Mastalab version: 1.8.3

**Comment by stom79** [comment] 2018-03-02 14:35
Did you try to click on the date "1d" it should display the full date. If not, it's a bug.

**Comment by PhotonQyv** [comment] 2018-03-02 14:48
It's a feature I contributed several versions back @jpdeplaix it's currently set to timeout after 5 seconds, and redisplay the approximate date/time. If you want it displayed longer let me know (:*

**Comment by jpdeplaix** [comment] 2018-03-02 15:04
Mmh, I see. So yes it's working but I feel like if you don't know this feature exists the majority of people wouldn't have guessed it was there :/ (at least I didn't)
I would personally think it would be better to display it every time for the current selected toot (in the bottom part like the webapp does).
Also if I try to click on the date while browsing my timeline I will end up opening the toot anyway as the area where I have to click is quite small or I have big fingers or something ^^"

**Comment by stom79** [comment] 2018-03-02 15:08
I will improve the layout of the current focused toot in a conversation but it's not limited to the date and it asks more work. I will reproduce what is done for the webapp.

> I have big fingers or something ^^
I don't want to say that, but currently I can't reproduce that bug :)

**Comment by stom79** [comment] 2018-04-25 11:57
OK. It will be in the next release.

**Closed by stom79** 2018-04-25 11:57 UTC
Labels: enhancement
