### ISSUE TITLE
Sharing toot includes whole text instead of link only

### ISSUE THREAD

**Issue by spectaculous** [stom79/mastalab#428] opened 2018-04-28 16:26 UTC
It seems like the sharing behavior changed. Now when I share a toot it includes the complete text and a link to the toot and media links. It used to be the link only, which I liked more.
Not sure this is intended. Maybe this could be a setting?
---

Mastalab version: 1.8.7.1, 1.8.8 (Play Store)
I think it changed in 1.8.6 I'm not sure

Android version: 8.1

**Comment by stom79** [comment] 2018-04-28 16:29
Yes, it was intended :)
https://github.com/stom79/mastalab/issues/303

I will introduce this as an option.

**Comment by spectaculous** [comment] 2018-04-28 16:35
Great! Thanks a lot :)

**Comment by stom79** [comment] 2018-05-12 09:12
Update is in #303 https://github.com/stom79/mastalab/commit/4240f504cfc84866c6f82a5c9be70a2890dc2edd
But the fix will be in the next release. You will have to uncheck the option.

**Closed by stom79** 2018-05-12 09:12 UTC
Labels: enhancement
