### ISSUE TITLE
Quite strange networking issues.

### ISSUE THREAD

**Issue by jfmcbrayer** [stom79/mastalab#47] opened 2017-11-17 13:56 UTC
I'm having a quite strange networking issue with mastalab, and I wonder if it might have some bearing on #37 and #44 .

Mastalab works fine on cellular (3G, don't @ me), and on the public wifi nearest my work. It does *not* work on my home wifi -- all connections time out. This is strange, because other Mastodon clients work fine on my home wifi, connecting to the same instances (Subway Tooter, web). 

If Mastalab is already signed in, it tries to fetch toots but just spins and eventually notifies that it can't connect to the network.

If Mastalab is *not* already signed in (I tried deleting the app's data to see if this would help), it gives the behaviour in the above bugs: no autocomplete, and typing instance names that can't be autocompleted don't enable the login button.

Not sure what other data I can send to help debug this.

**Comment by stom79** [comment] 2017-11-18 18:09
Could you please check if it's fixed in [1.6.0-rc-1](https://github.com/stom79/mastalab/releases/tag/1.6.0-rc-1). APKs can be downloaded on this page.

**Comment by jfmcbrayer** [comment] 2017-11-19 14:50
This version does fix that issue. However, (I believe), it introduces new ones. In particular, media uploads do not complete.

**Comment by stom79** [comment] 2017-11-19 14:55
There was a bug with this release when there was more than one media (it only kept the last one). It's [fixed](https://github.com/stom79/mastalab/blob/develop/app/fdroid/release/app-fdroid-release-1.6.0-rc-1-fix3.apk?raw=true) 
It also fixes the bug when loading more toots and when sharing url.

**Comment by jfmcbrayer** [comment] 2017-11-19 16:08
The issue with not saving media is not fixed in release 1.6.0. It happens with a single media -- I click to upload a photo, select it, and the progress bar runs to 100%. However, the image is not displayed in the toot composing activity, and if I post it, it is posted without the image.

(I'm not trying to be a demanding user; I'm trying to be helpful.)

**Comment by stom79** [comment] 2017-11-19 16:17
Sorry, I closed the issue because it was relative to the login issue. 

` I'm trying to be helpful`

You are :)

I got an issue with media and I thought you talked about this one.

Could you tell me what instance and Android version do you use? I will try to reproduce this bug. Thanks

**Comment by jfmcbrayer** [comment] 2017-11-19 17:09
I am on glitch.social, and Android is 7.1 (LineageOS 14.1).

On November 19, 2017 11:17:36 AM EST, Thomas <notifications@github.com> wrote:
>Sorry, I closed the issue because it was relative to the login issue. 
>
>` I'm trying to be helpful`
>
>You are :)
>
>I got an issue with media and I thought you talked about this one.
>
>Could you tell me what instance and Android version do you use? I will
>try to reproduce this bug. Thanks
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/stom79/mastalab/issues/47#issuecomment-345528705

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stom79** [comment] 2017-11-19 17:17
Can you reproduce this bug for all media?

**Comment by jfmcbrayer** [comment] 2017-11-19 18:12
Uploading a video, it gets to 100%, and then pops up a toast saying "oops, an error occurred". I think that with the image, I don't get the toast. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stom79** [comment] 2017-11-20 06:07
Could you clear the cache - deinstall/reinstall the app and check if you can upload?

**Comment by jfmcbrayer** [comment] 2017-11-20 13:19
Okay, I've tried this (deleted data from applications control panel), but it did not change the behaviour.

**Comment by stom79** [comment] 2017-11-21 17:27
@jfmcbrayer the problem occurs on some instances. It's due chunks of the file during upload. I am on it.

**Comment by stom79** [comment] 2017-11-22 08:05
@jfmcbrayer Could you please try this [release](https://github.com/stom79/mastalab/blob/develop/app/safetynet/release/app-safetynet-release-1.6.1-fix-test.apk?raw=true)? Thanks.

**Closed** 2017-11-22 10:00 UTC
Labels: good first issue

**Comment by jfmcbrayer** [comment] 2017-11-22 20:45
It works for me, thanks.
